# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Tree
version:      4.4
version_from: lib/Tk/Tree.pm
installdirs:  site
requires:
    Tk:                            800.024
    Tk::HList:                     4.014

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
